version: '3'

services:
  db:
    image: postgres:15
    container_name: db_app
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./search/config/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
    networks:
      - es-net

  kibana:
    image: kibana:8.8.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - es-net

networks:
  es-net:
    driver: bridge