version: '3'

services:
  db:
    image: postgres:15
    container_name: db_app
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
