"""product_name_max_length

Revision ID: 9a2829af81b1
Revises: 70208a8a94e7
Create Date: 2023-08-29 16:00:17.256060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2829af81b1'
down_revision = '70208a8a94e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
