"""product_max_length

Revision ID: bb9035f23fb6
Revises: 70208a8a94e7
Create Date: 2023-08-29 16:59:30.212785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9035f23fb6'
down_revision = '70208a8a94e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Product', 'name',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Product', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=35),
               existing_nullable=False)
    # ### end Alembic commands ###
